from typing import Union
from types import ModuleType
import importlib
import os.path

from .gen import *

__all__ = ['format_type_hints', 'write_type_stub']

def write_type_stub(
	module: Union[ModuleType, str],
	output_path: Union[str, None] = None,
):
	'''
	Convenience interface that creates a full type stub file
	for a module generated by ffibuilder. The module can be
	given either as a name to import, or directly as a module
	object. By default the stub file is placed next to the module
	with a `.pyi` extension.
	'''

	if isinstance(module, str):
		module = importlib.import_module(module)
	if output_path == None:
		file = module.__file__
		assert file != None, f'{module!r} has no __file__'
		dirname, basename = os.path.split(file)
		assert '.' in basename
		output_path = os.path.join(dirname, basename.split('.')[0] + '.pyi')
	hints = format_type_hints(module.ffi) + '\n\n' 'ffi: FFI' '\n'
	if hasattr(module, 'lib'):
		hints += 'lib: Lib' '\n'
	with open(output_path, 'w') as f:
		f.write(hints)
