from typing import TypeAlias, Self, Iterator, Union, Any, Literal, Callable, overload
from types import TracebackType
import _cffi_backend
# needed for conditional definitions in FFI, see below
import sys

class _CDataBase:
	def __enter__(self) -> Self: ...
	def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: TracebackType | None, /) -> None: ...

	def __bool__(self) -> bool: ...
	def __hash__(self) -> int: ...

class IntPrimitive(_CDataBase):
	def __int__(self) -> int: ...
	def __eq__(self, other: IntPrimitive, /) -> bool: ...
	def __ne__(self, other: IntPrimitive, /) -> bool: ...
	def __ge__(self, other: IntPrimitive, /) -> bool: ...
	def __gt__(self, other: IntPrimitive, /) -> bool: ...
	def __le__(self, other: IntPrimitive, /) -> bool: ...
	def __lt__(self, other: IntPrimitive, /) -> bool: ...

class FloatPrimitive(_CDataBase):
	def __int__(self) -> int: ...
	def __float__(self) -> float: ...
	def __eq__(self, other: IntPrimitive, /) -> bool: ...
	def __ne__(self, other: IntPrimitive, /) -> bool: ...
	def __ge__(self, other: IntPrimitive, /) -> bool: ...
	def __gt__(self, other: IntPrimitive, /) -> bool: ...
	def __le__(self, other: IntPrimitive, /) -> bool: ...
	def __lt__(self, other: IntPrimitive, /) -> bool: ...

class ComplexPrimitive(_CDataBase):
	def __complex__(self) -> complex: ...
	def __eq__(self, other: IntPrimitive, /) -> bool: ...
	def __ne__(self, other: IntPrimitive, /) -> bool: ...
	def __ge__(self, other: IntPrimitive, /) -> bool: ...
	def __gt__(self, other: IntPrimitive, /) -> bool: ...
	def __le__(self, other: IntPrimitive, /) -> bool: ...
	def __lt__(self, other: IntPrimitive, /) -> bool: ...

class PointerBase[T](_CDataBase):
	""" Used for all pointers, including those pointing to unsized types, which have restricted operations. """
	def __eq__(self, other: PointerBase[Any], /) -> bool: ...
	def __ne__(self, other: PointerBase[Any], /) -> bool: ...
	def __ge__(self, other: PointerBase[Any], /) -> bool: ...
	def __gt__(self, other: PointerBase[Any], /) -> bool: ...
	def __le__(self, other: PointerBase[Any], /) -> bool: ...
	def __lt__(self, other: PointerBase[Any], /) -> bool: ...

class Pointer[T](PointerBase[T]):
	""" Pointer to a sized type. """
	def __add__(self, other: int, /) -> Pointer[T]: ...
	def __radd__(self, other: int, /) -> Pointer[T]: ...
	@overload
	def __sub__(self, other: int, /) -> Pointer[T]: ...
	@overload
	def __sub__(self, other: Pointer[T], /) -> int: ...
	# FIXME: make cffi actually raise in the unsized case
	@overload
	def __getitem__(self, index: int) -> T: ...
	@overload
	def __getitem__(self, index: slice) -> Array[T]: ...
	@overload
	def __setitem__(self, index: int, value: T) -> None: ...
	@overload
	def __setitem__(self, index: slice, value: Array[T]) -> None: ...

class Array[T](Pointer[T]):
	def __len__(self) -> int: ...
	def __iter__(self) -> Iterator[T]: ...

ErrorCallback: TypeAlias = Callable[[Exception, Any, TracebackType], Any]
