[project]
name = "cffi-mkstub"
version = "0.0.2"
authors = [
  { name="Alba Mendez", email="me@alba.sh" },
]
description = "Type stub generator for cffi modules"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Typing :: Typed",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Code Generators",
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

[project.scripts]
cffi-mkstub = "cffi_mkstub.__main__:main"

[project.urls]
Homepage = "https://github.com/mildsunrise/cffi-mkstub"
Issues = "https://github.com/mildsunrise/cffi-mkstub/issues"
